### ISSUE TITLE
GameUI for Template needs work.

### ISSUE THREAD

**Issue by reepblue** [Enhanced-Source-Project/Enhanced-Source#1]
This is the most annoying thing about this branch, and that is that you need to create your own GameUI for your mods. The template supplies the user with a standard one with a bik movie in the main menu, options, etc. But a lot of things where "hacked" to work properly.

First notice that under vloadingprogress.cpp I added [code]

```
// HACK! if we are in game and the progress bar is done, close the loading screen.
if (!engine->IsInGame() && (GetProgress() >= 0.85f)) //<- any later and this function does not call.
{
    if ( UI_IsDebug() )
    {
        Msg( "[GAMEUI] loadingProgress::OnThink() calling OnLevelLoadingFinished\n");
    }

    m_bLoadedFully = true;
    //CBaseModPanel::GetSingleton().OnLevelLoadingFinished( 0 );
}
```

This compares with the base panel and it will close when the player is in game, and the loading progress is at the latest progress in which it's still responsive (Which is 85%). Not having this here, the loading screen stands even though the map is loaded, and the game is playable. This still happens under tools mode. 

Other improvements needed is to have the mouse options not use the older panels, and to make all of the GameUI colors changeable in the menuscheme.res file. Right now, it's good, but it needs to be better. We also have an issue when the SteamOverlay closes in game, the cursor is still drawn.

**Comment by DankParrot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/TQQQtyBS/1-test)
