### ISSUE TITLE
Pixel light falloff is incorrect

### ISSUE THREAD

**Issue by DankParrot** [Enhanced-Source-Project/Enhanced-Source#17]
Note the dark area at the edge between the floor and the wall.

![Image](http://dankparrot.xyz/i/bcfld.jpg)

**Comment by DankParrot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Point Light Falloff](https://trello.com/c/jn21vj7g/6-point-light-falloff)

**Comment by Joshua-Ashton** [comment]
Turned out its actually correct.
