### ISSUE TITLE
Playing a commentary node crashes the game.

### ISSUE THREAD

**Issue by reepblue** [Enhanced-Source-Project/Enhanced-Source#2]
Apparently in in cdll_client_int.cpp, at  line 2286:

pNetworkable->OnDataChanged(pEvent->m_UpdateType);

The game crashes on playing a commentary node. Not sure if it's this line exactly being that the host function it's almost one to one with Source 2007/2013, minus the stuff about splitscreen.

**Comment by DankParrot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Commentary Node Crash](https://trello.com/c/cTJsglrp/2-commentary-node-crash)
