### ISSUE TITLE
[REQUEST] Normal map support for overlays

### ISSUE THREAD

**Issue by GamerDude27** [Enhanced-Source-Project/Enhanced-Source#32]
Title

![download](https://user-images.githubusercontent.com/5366524/29495675-20034af0-85c4-11e7-8b97-1b299e3b34e6.jpg)

**Comment by DasMaddi** [comment]
DecalModulate provides a similar and very effective illusion. Adding normal maps for overlays would require an extensive amount of shader rewriting, which is not currently feasible.

https://developer.valvesoftware.com/wiki/Decals#DecalModulate
