### ISSUE TITLE
Swarm.exe is detected as a virus

### ISSUE THREAD

**Issue by TurtleMaker** [Enhanced-Source-Project/Enhanced-Source#39]
When I try to run a game with Enhanced Source the swarm.exe file gets deleted because it's detected as a virus

**Comment by Joshua-Ashton** [comment]
Don't use a shit anti virus.

**Comment by TedsterTech** [comment]
@Joshua-Ashton and probably with good reason!
Could some Windows Defender setups also decide it's malicious?
