### ISSUE TITLE
Loading saves on any base other than HL2 crashes

### ISSUE THREAD

**Issue by brushtool** [Enhanced-Source-Project/Enhanced-Source#52]
Haven't tested it on Portal, but it might work, because it seems to crash with the sdk_ cpp files.

**Comment by GodLeaveMe** [comment]
> Haven't tested it on Portal, but it might work, because it seems to crash with the sdk_ cpp files.

The author of the project seems to be absent now.

**Comment by DasMaddi** [comment]
I will take a look at this soon

**Comment by DasMaddi** [comment]
I have been testing stock versions of the deferred, portal, and regular templates, but have not been able to reproduce the issue. Could you describe the events up to the crash and what map you are saving/restoring?

**Comment by DasMaddi** [comment]
Closing per no response/reproduction available.
